#' Convert Continuous Predicted Values to Binary Based on MaxEnt Thresholds
#'
#' This function takes the continuous predicted values generated by MaxEnt for a species,
#' applies 11 threshold values provided by MaxEnt, and returns a data.frame with binary
#' values for each threshold along with the coordinates.
#'
#' @param model_dir The directory containing MaxEnt modeling results (default is "models").
#' @param predicted_dir The directory containing continuous predicted values (default is "results/gis/prediction_avg").
#' @param species_name The species identifier used for the model folder and predicted values. It serves as the unique name associated with the species throughout the modeling and mapping process.
#'
#' @return A data.frame with binary values for each threshold and coordinates.
#'
#' @examples
#' \dontrun{
#' # Example usage:
#' model2binary_tb(model_dir = "models", predicted_dir = "results/gis/prediction_avg", species_name = "Species_A")
#' }
#'
#' @importFrom raster rasterToPoints
#' @importFrom data.table fread as.data.table setDT melt
#'
#' @export
model2binary_tb <-
  function(model_dir = "models",
           predicted_dir = "results/gis/prediction_avg",
           species_name) {

    # import continuous predicted value of SDM
    predicted_value <-
      readRDS(sprintf("%s/%s.rds", predicted_dir, species_name)) %>%
      rasterToPoints %>%
      as.data.table

    # threshold data from MaxEnt results
    r <- length(list.files(sprintf("%s/%s/", model_dir, species_name)))

    thresholds <-
      lapply(1:r, function(r)
        fread(sprintf("%s/%s/%02d/maxentResults.csv",
                      model_dir, species_name, r)
        )
      ) %>%
      do.call(rbind, .) %>%
      .[, colnames(.) %like% "Cloglog threshold", with = FALSE] %>%
      .[, lapply(.SD, mean, na.rm = TRUE)] %>%
      data.table::melt(measure = patterns("Cloglog threshold"),
                       variable.name = "threshold",
                       value.name = "value") %>%
      setDT


    # add binary value to predicted table
    # use `:=` will add column to original data.table
    threshold_list <-
      thresholds$threshold

    add_binary_value <-
      lapply(seq_along(threshold_list),
             function(n){

               threshold_value <- thresholds$value[n]
               threshold_name <- thresholds$threshold[n] %>% as.character()

               bi <-
                 predicted_value[, value := ifelse(layer >= threshold_value, 1, 0)] %>%
                 data.table::setnames("value", threshold_name)

               return(NULL)
             })

    return(predicted_value)
  }
